-  name: install java on ubuntu machine 
   become : yes
   hosts: all 
   tasks: 
    - name: java installation
      ansible.builtin.apt :
        name : install openjdk-11-jdk
        state : present
      

