-  name: install java on ubuntu machine 
   become : yes
   hosts: all 
   tasks: 
    - name: java installation
      ansible.builtin.apt :
        name : openjdk-11-jdk
        state : present
    - name: create a tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create a tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
      

