-  name: install java on ubuntu machine 
   become : yes
   hosts: all 
   tasks: 
    - name: java installation
      ansible.builtin.apt :
        name : openjdk-11-jdk
        state : present
    - name : add group 
      ansible.builtin.group : 
       name : tomcat
       state : present    
    - name : user creation for tomcat
      ansible.builtin.user : 
        name : tomcat
        create_home : true
        group : tomcat
        home : /opt/tomcat
        shell : /bin/false
        state : present 
    - name : download tomcat
      ansible.builtin.get_url : 
        url : https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.4/bin/apache-tomcat-10.1.4.tar.gz
        dest : /tmp/apache-tomcat-10.1.4.tar.gz