-  name : install mysql on ubuntu 
   hosts : all 
   become : yes 
   tasks : 
    - name : Download mysql
      ansible.builtin.get_url : 
        url : http://dev.mysql.com/get/Downloads/MySQL-5.0/MySQL-server-community-5.0.37-0.rhel4.i386.rpm/from/http://mirrors.dedipower.com/www.mysql.com/
        dest : /tmp/   
      


